### DISCUSSION TITLE
Edk2-Pytools v1.0.0

### DISCUSSION THREAD

**Discussion by Javagedes** [tianocore/edk2-pytool-extensions#562] [Ideas]
This is a discussion on the current proposal of Edk2-Pytool modifications necessary for a v1.0.0 release. Please find the attached document for the proposal.

Please provide feedback on current proposed changes, any additional changes you would like to see, and any User stories missed that need to be accounted for.

[Edk2-Pytools Proposal.docx](https://github.com/tianocore/edk2-pytool-extensions/files/11567589/Edk2-Pytools.Proposal.docx)

## Proposals
1. Convert `stuart_<cmd>` to `stuart <cmd>`.
2. Merge `stuart_setup` and `stuart_ci_setup` into `stuart_init`.
3. Remove Settings Managers, using Toml based configuration instead.
4. replace `stuart_ci_build` with `--checks` flag for `stuart_build`.
5. Add advanced configurability to python logging
6. Move to pythonic way of error and exception handling
7. move to pythonic style guide (snake_case functions)

### Introduce command aliasing
It was requested by multiple people to a multiple build paradigm, or the ability to call invocables from other invocables. The current idea is to add command alias's to the configuration files as it allows the flexibility of developers to create combinations of commands as they see fit. This would probably be in a 1.1.0 release as a new feature rather than a part of the 1.0.0 release, but could be very beneficial.

Below would be an example of adding an alias to run `stuart update` and `stuart build` through an alias
``` toml
[Alias.<os>?]
# stuart switch_build PlatformPkg1 -> stuart update -p PlatformPkg1; stuart build -p PlatformPkg1
switch_build = "stuart update -p {0}; stuart build -p {0}"

# stuart switch_build -p PlatformPkg1 -> stuart update -p PlatformPkg1; stuart build -p PlatformPkg1
switch_build = "stuart update -p {-p}; stuart build -p {-p}"
```

This can already be easily done on a user-by-user basis through scripts, but by enabling it in the configuration file, that functionality can easily be shared across a dev team where applicable. More thought will need to be put into this to ensure complex aliasing can be handled

### Configuration Chaining 
The original idea was to provide a singular override for configurations (repository level and package level override). It was brought up that additional override levels would be beneficial. The new idea is to follow the folder hierarchy up to the workspace root and overriding any configs along the way.
